#ifndef GRAPES_GRAPES_CGRAPH_MACROS_H_
#define GRAPES_GRAPES_CGRAPH_MACROS_H_

#define PI 3.14159265358979323846

#define GRAPES_NO_NODE -1
#define GRAPES_INIT_NODE -2
#define GRAPES_FALSE 0
#define GRAPES_TRUE 1
#define GRAPES_RED 0
#define GRAPES_BLUE 1
#define GRAPES_NO_COLOR -1

#endif  // GRAPES_GRAPES_CGRAPH_MACROS_H_